### ISSUE TITLE
Unable to add a source via the bookmarklet, invalid CSRF token

### ISSUE THREAD

**Issue by asvc** [themarshallproject/klaxon#324]
I have deployed Klaxon to Heroku using the provided instruction (much appreciated!), but can't make the bookmarklet work.

After selecting part of the page and entering an e-mail, 422 error is returned with the following in the console log:
```js
HTTP422: UNPROCESSABLE ENTITY - The request was well-formed but could not be processed due to semantic errors.
POST - https://app.herokuapp.com/login?return_to=https%3A%2F%2Fapp.herokuapp.com%2Fembed%2Fiframe%3Furl%3Dhttps%253A%252F%252Fwww.example.com
```

Relevant output from the app. log at Heroku:
```log
2020-04-15T12:58:23.878036+00:00 app[web.1]: Can't verify CSRF token authenticity.

2020-04-15T12:58:23.878396+00:00 app[web.1]: Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms)

2020-04-15T12:58:23.879134+00:00 app[web.1]:   

2020-04-15T12:58:23.879164+00:00 app[web.1]: ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):

2020-04-15T12:58:23.879182+00:00 app[web.1]:   

2020-04-15T12:58:23.879250+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'

2020-04-15T12:58:23.879251+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'

2020-04-15T12:58:23.879251+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'

2020-04-15T12:58:23.879252+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'

2020-04-15T12:58:23.879252+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'

2020-04-15T12:58:23.879253+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'

2020-04-15T12:58:23.879253+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:199:in `block in halting'

2020-04-15T12:58:23.879254+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'

2020-04-15T12:58:23.879254+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:513:in `each'

2020-04-15T12:58:23.879254+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:513:in `invoke_before'

2020-04-15T12:58:23.879255+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:131:in `run_callbacks'

2020-04-15T12:58:23.879255+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/abstract_controller/callbacks.rb:41:in `process_action'

2020-04-15T12:58:23.879255+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/rescue.rb:22:in `process_action'

2020-04-15T12:58:23.879256+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'

2020-04-15T12:58:23.879256+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `block in instrument'

2020-04-15T12:58:23.879256+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'

2020-04-15T12:58:23.879256+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `instrument'

2020-04-15T12:58:23.879256+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'

2020-04-15T12:58:23.879257+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'

2020-04-15T12:58:23.879257+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2.1/lib/active_record/railties/controller_runtime.rb:24:in `process_action'

2020-04-15T12:58:23.879257+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/abstract_controller/base.rb:134:in `process'

2020-04-15T12:58:23.879257+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionview-5.2.2.1/lib/action_view/rendering.rb:32:in `process'

2020-04-15T12:58:23.879257+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_controller/metal.rb:191:in `dispatch'

2020-04-15T12:58:23.879257+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_controller/metal.rb:252:in `dispatch'

2020-04-15T12:58:23.879258+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'

2020-04-15T12:58:23.879258+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/routing/route_set.rb:34:in `serve'

2020-04-15T12:58:23.879258+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/journey/router.rb:52:in `block in serve'

2020-04-15T12:58:23.879258+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/journey/router.rb:35:in `each'

2020-04-15T12:58:23.879258+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/journey/router.rb:35:in `serve'

2020-04-15T12:58:23.879258+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/routing/route_set.rb:840:in `call'

2020-04-15T12:58:23.879259+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-cache-1.9.0/lib/rack/cache/context.rb:140:in `forward'

2020-04-15T12:58:23.879259+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-cache-1.9.0/lib/rack/cache/context.rb:147:in `pass'

2020-04-15T12:58:23.879259+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-cache-1.9.0/lib/rack/cache/context.rb:159:in `invalidate'

2020-04-15T12:58:23.879259+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-cache-1.9.0/lib/rack/cache/context.rb:74:in `call!'

2020-04-15T12:58:23.879260+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-cache-1.9.0/lib/rack/cache/context.rb:51:in `call'

2020-04-15T12:58:23.879260+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/tempfile_reaper.rb:15:in `call'

2020-04-15T12:58:23.879260+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/etag.rb:25:in `call'

2020-04-15T12:58:23.879261+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:38:in `call'

2020-04-15T12:58:23.879264+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'

2020-04-15T12:58:23.879264+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'

2020-04-15T12:58:23.879264+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'

2020-04-15T12:58:23.879264+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'

2020-04-15T12:58:23.879264+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'

2020-04-15T12:58:23.879265+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'

2020-04-15T12:58:23.879265+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:98:in `run_callbacks'

2020-04-15T12:58:23.879265+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'

2020-04-15T12:58:23.879265+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'

2020-04-15T12:58:23.879265+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'

2020-04-15T12:58:23.879266+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:38:in `call_app'

2020-04-15T12:58:23.879266+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:26:in `block in call'

2020-04-15T12:58:23.879266+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'

2020-04-15T12:58:23.879266+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'

2020-04-15T12:58:23.879266+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'

2020-04-15T12:58:23.879267+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/rack/logger.rb:26:in `call'

2020-04-15T12:58:23.879267+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'

2020-04-15T12:58:23.879267+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'

2020-04-15T12:58:23.879267+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'

2020-04-15T12:58:23.879267+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'

2020-04-15T12:58:23.879268+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/activesupport-5.2.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'

2020-04-15T12:58:23.879268+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'

2020-04-15T12:58:23.879268+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/static.rb:127:in `call'

2020-04-15T12:58:23.879268+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'

2020-04-15T12:58:23.879268+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.2.1/lib/action_dispatch/middleware/ssl.rb:74:in `call'

2020-04-15T12:58:23.879269+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/railties-5.2.2.1/lib/rails/engine.rb:524:in `call'

2020-04-15T12:58:23.879269+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'

2020-04-15T12:58:23.879269+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'

2020-04-15T12:58:23.879269+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'

2020-04-15T12:58:23.879269+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'

2020-04-15T12:58:23.879270+00:00 app[web.1]: vendor/bundle/ruby/2.4.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

Running on "heroku-18" stack. Can reproduce on the latest Firefox ESR and MS Edge.

**Comment by asvc** [comment]
Fixed with selective white-listing.

**Comment by walinchus** [comment]
What does that mean? I am having this same error. @asvc

**Comment by asvc** [comment]
@walinchus , try whitelisting its address (3rd-party cookies) in your web-browser. For example, Firefox:
![image](https://user-images.githubusercontent.com/300146/81475472-9815f600-924b-11ea-82d9-a7d7a743297c.png)

That being said, looking at [security-relevant](https://github.com/themarshallproject/klaxon/pulls?q=is%3Aopen+is%3Apr+label%3Asecurity) pull requests you might be careful as to where you host it and what data is exposed.

**Comment by walinchus** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/25959269/81475958-3fa80f80-91dd-11ea-9d9c-c3263653587b.png">
Hmm. I am still getting the same error. But thank you for helping! Any other possibilities I could try?

**Comment by asvc** [comment]
@walinchus , I should have clarified. Please enter address of _your_ Klaxon installation.

**Comment by walinchus** [comment]
@asvc Thanks so much for helping with this. I'm not sure why I can't quite get it! When you say your Klaxon installation, you mean https://github.com/eye-on-ohio/klaxon, right? I tried that but I still get the same error. 

Oddly enough though I can still add an address manually, thought that only works for like, a whole domain and not a specific selector if that makes any sense.

**Comment by GabeIsman** [comment]
@walinchus Your klaxon installation has a URL that will look something like `<the-name-you-chose>.herokuapp.com`. You might also try in another browser. The various browsers have different default policies around third-party cookies. I need to some investigation at some point to write some more comprehensive documentation. Sorry for the difficulty, these policies have been changing a bit over the last year or so.

**Comment by walinchus** [comment]
*Hmm good news and bad news. *


*The bad is that it didn't work in firefox. The good news is that it now
works perfectly in Google Chrome. So my guess is there's an additional
firefox setting that might hinder it. *
